# language php
language: php
php:
- 5.5
- 5.4
- hhvm
# Notifications
notifications:
  flowdock:
    secure: QOArjMZ42xRjGPbqQwGm8xpaEGOe2M1Z8OB58zAnHRcxhfhmewiM/F73D6kVkDIUWe7PbaG9z3WZt+x0I0wu7wXdzjTq1lCA+e0B8xZFNxHtSzrbBm6frVbvDS9/j45HXQPxFhb98aJm/3KwegqPKQd/2jXy1DqNlwlrgIU81Ok=
  email:
  - secure: cuIQFttoMDtatAYye2MZ6dle2b4uXmCOQiLTzlzDmu0vYxNnEwjxwlGvcXHFyXVrZXe/NoXKqdYSWR9QEHAvvsOyfHbU+BjYt/faw7wBFYoc6BBntTc9ytI965QUzFb56xrI6J1j9CwO7c+8Ih+okmS0sDWmBrT7mSmCdUlMucE=
# start unit tests
script:
  - >
    echo;
    echo "Running unit tests";
    phpunit --bootstrap tests/phpunit_bootstrap.php  tests/
  - >
    echo;
    echo "Running php lint";
    /bin/bash -c "
      if ! find lib/ -name \*.php | parallel --gnu 'php -l {}' > /tmp/errors 2>&1; then
        grep -v \"No syntax errors detected in\" /tmp/errors;
        exit 99;
      fi
    "